### ISSUE TITLE
links on HN

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/Marketing-and-Branding#13]
To publish my website and first blog post in Hacker News to see what reception I get

**Comment by pratik-IDWT** [comment]
Posted on HN - https://news.ycombinator.com/newest:

https://news.ycombinator.com/from?site=indatawetrust.co.uk 



![Image](https://user-images.githubusercontent.com/112123058/191927229-e710dcb3-8629-4674-96ab-8d22973512b7.png)

**Comment by pratik-IDWT** [comment]
@nelsonic  please upvote :) https://news.ycombinator.com/from?site=indatawetrust.co.uk

**Comment by nelsonic** [comment]
This is what I see when I click that link:
![image](https://user-images.githubusercontent.com/194400/191936380-5a5d3640-999e-449c-a462-5db7a6cb65ca.png)

If you have a direct link to the item I can read, upvote and comment. 👌

**Comment by nelsonic** [comment]
Guessing you're working on the DNS ... ?

![image](https://user-images.githubusercontent.com/194400/191937322-f7d8a9d8-f6ab-449f-8559-ff3ff6c0fb23.png)

**Comment by pratik-IDWT** [comment]
@nelsonic , someone pointed out the DNS/rooting issue I have. 

If I type it without www then it errors. I'll be taking a look when back 👍🏽
