### ISSUE TITLE
Write Down the Company Goals and Objectives

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/Marketing-and-Branding#17]
Where do I want the company to be in the future and how large. 

Refer to First Chapter in Start Small, Stay Small to Define - https://github.com/In-Data-We-Trust/Marketing-and-Branding/issues/18

**Comment by nelsonic** [comment]
Great book. 👌
Looking forward to reading your goals. 💭

**Comment by pratik-IDWT** [comment]
Goals have been captured here - https://github.com/In-Data-We-Trust/Marketing-and-Branding/blob/main/Company_Goals.md

Will leave open for a few days incase I want to update or change them.
