### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/Marketing-and-Branding#26]
Make a list of people to reach out to for testimonials of previous work

- Tim D
- Nick Moss
- Nick Baker
- Simon Bateman
- Who else?
- @nelsonic

**Comment by pratik-IDWT** [comment]
These are growing which are making me blush! 



![Image](https://user-images.githubusercontent.com/112123058/218814014-4e9f5c7a-6657-4a7d-95df-f78f47a0cd80.png)



Next - Need to Ask Simon B, however he is a CTO, so is very busy so I will need to draft it. Time to get creating

**Comment by pratik-IDWT** [comment]
@nelsonic , What is the most appropriate title I can tag your lovely testimonial too? 

![Image](https://user-images.githubusercontent.com/112123058/221646350-37f83eb6-69dc-44de-ac72-0877af53d526.png)

**Comment by nelsonic** [comment]
Hey @pratik-IDWT, 👋 
Principal Technical Consultant or CTO. 🧑‍💻
