### ISSUE TITLE
Draft post to share the website on LinkedIn

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/Marketing-and-Branding#33]
I will be publishing my home page on Linkedin shortly, which needs a great message to announce to my network! 

Will get drafting some content and look at previous posts from others for inspiriation

**Comment by pratik-IDWT** [comment]
Example shared from Max previously



![Image](https://user-images.githubusercontent.com/112123058/229609397-0de9ee75-5fe7-4796-b3c2-a2581228874e.png)

**Comment by pratik-IDWT** [comment]
## Draft of LinkedIn Post

I am excited to announce the creation and launch of In Data We Trust - https://www.indatawetrust.co.uk/

A consultancy that helps clients utilise data strategies to fuel their growth. 

I'll be sharing content from the website over a series of posts.

**Comment by pratik-IDWT** [comment]
# Few more Drafts of posts to share on LinkedIn

## Draft 2

I am excited to announce the launch of In Data We Trust - https://www.indatawetrust.co.uk/

A Data Consultancy that helps you utilise your data to drive business strategies

## Draft 3

I am excited to announce the launch of In Data We Trust - https://www.indatawetrust.co.uk/

I'll be sharing content from the website over a series of posts on Linkedin, aiming to highlight how we work and how we can help you on your data journey

**Comment by pratik-IDWT** [comment]
@nelsonic  - Care to provide your creative sprit on crafting a few words to post on LinkedIn?

I'll aim to share the 3 links on [here](https://github.com/In-Data-We-Trust/Marketing-and-Branding/blob/main/Website_Page_tracker.md), whilst building on the additional 3 pages so they are ready to post.

**Comment by pratik-IDWT** [comment]
A LinkedIn post wording that I can use as reference. Saving here for noting later

 ![Screenshot_20230416-094055.png](https://user-images.githubusercontent.com/112123058/232287160-1ac23b97-fb51-400f-a39c-f1d32bdbe552.png)

**Comment by pratik-IDWT** [comment]
## Draft 4 

Excited to share that over the last few months, I have been building a Data Consultancy 

## Draft 5

Excited to share that over the last few months, I have spent my free time building a Data Consultancy - https://www.indatawetrust.co.uk/

One that focuses on making the complicated simple for start ups or scaling organisations.

**Comment by pratik-IDWT** [comment]
And lastly, here's one written for my by Chatgpt 

`Excited to Announce the Launch of [Your Data Consultancy Name]! 🚀🎉

I am thrilled to share that I have officially launched [Your Data Consultancy Name], a new venture dedicated to helping businesses harness the power of data to drive success. As a data consultant with years of experience in the industry, I am passionate about helping organizations leverage data to make informed decisions, optimize operations, and achieve their business objectives.

In today's data-driven world, organizations of all sizes and across industries need to unlock the true potential of their data. Data holds the key to unlocking valuable insights, identifying patterns, and uncovering opportunities for growth. However, many businesses struggle to fully leverage their data due to challenges such as data quality issues, lack of data governance, and limited expertise in data analysis and interpretation.

That's where [Your Data Consultancy Name] comes in. Our mission is to empower businesses with data-driven decision-making by providing expert data consulting services tailored to their unique needs. We offer a wide range of services, including data strategy and planning, data management and governance, data analytics and visualization, and data-driven insights and recommendations.

With [Your Data Consultancy Name], you can expect:

🔍 Data-driven Solutions: We work closely with you to understand your business goals and challenges, and develop customized data strategies and solutions that align with your specific needs and objectives.

📈 Actionable Insights: Our team of skilled data analysts and consultants use cutting-edge tools and techniques to analyze your data and extract meaningful insights that drive action and create value for your business.

💼 Practical Approach: We understand that every business is unique, and our approach is practical and results-oriented. We focus on delivering tangible outcomes that directly impact your bottom line and help you achieve your business goals.

🔒 Data Security and Privacy: We prioritize data security and compliance, and adhere to industry best practices to protect your data and ensure confidentiality and privacy.

I am truly excited about this new venture and look forward to partnering with businesses to help them unlock the power of their data. Whether you are a small start-up or a large enterprise, data can be a game-changer for your business, and I am here to help you harness its full potential.

If you are interested in learning more about how [Your Data Consultancy Name] can enable your business through data, please don't hesitate to reach out. Let's embark on this data-driven journey together!

#DataConsulting #DataDrivenDecisions #BusinessGrowth #DataStrategy #DataAnalytics #DataInsights`

**Comment by pratik-IDWT** [comment]
## Final Post written with aid of chatgpt 

I am excited to announce the launch of In Data We Trust! - https://www.indatawetrust.co.uk/

I am thrilled to share that I have officially launched In Data We Trust, a new venture dedicated to helping businesses harness the power of data to drive success. As a data consultant with years of experience in the industry, I am passionate about helping organizations leverage data to make informed decisions, optimize operations, and achieve their business objectives.

Our mission is to empower businesses with data-driven decision-making by providing expert data consulting services tailored to their unique needs. We offer a wide range of services, including data strategy and planning, data management and governance, data analytics and visualization, and data-driven insights and recommendations.

#DataConsulting #DataDrivenDecisions #BusinessGrowth #DataStrategy #DataAnalytics #DataInsights

**Comment by pratik-IDWT** [comment]
Marking as complete as the post is due to be published on Tuesday morning at 7.30am BST 🚀

**Comment by nelsonic** [comment]
@pratik-IDWT final post looks great. 
Apologies for not seeing the mention above sooner. 
Ping me when you post it so I can "like". 👍

**Comment by pratik-IDWT** [comment]
## Final Update

Post shared on Linkedin finally! - https://www.linkedin.com/posts/pratikpatel89_in-data-we-trust-activity-7056514679929479168-v4ML?utm_source=share&utm_medium=member_desktop

Has been well received - need to keep up the PR and try to generate some leads next



![Image](https://user-images.githubusercontent.com/112123058/234977501-8e82090e-a121-40f6-8e6d-a6687b004c36.png)
